[server]
host = "0.0.0.0"
port = 54604
base_url = "/request"

[navidrome]
DbPath = "/var/lib/navidrome/navidrome.db"
PasswordEncryptionKey = "just for obfuscation"

[qobuz]
email = "l07zxmprh6@maili.fun"
password = "5bxm98YMua"
DownloadPath = "/mnt/disk4/music"
DbPath = "~/.config/qobuz-dl/qobuz-dl.db"